apiVersion : apps/v1
kind: Deployment
metadata:
  name: hnltop 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hnltop
  template:
    metadata:
      labels:
        app: hnltop 
    spec:
      containers:
        - name: hnltop 
          image: epamdiplomaacr.azurecr.io/hnltop
          ports:
          - containerPort: 5000