apiVersion : apps/v1
kind: Deployment
metadata:
  name: hnlapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hnlapp
  template:
    metadata:
      labels:
        app: hnltop 
    spec:
      containers:
        - name: hnlapp
          image: epamdiplomaacr.azurecr.io/nhlapp
          ports:
          - containerPort: 5000
