on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: epamdiplomaacr
  CLUSTER_NAME: akstest
  CLUSTER_RESOURCE_GROUP: EPAM_Diploma
  NAMESPACE: nhlstat
  SECRET: nhltauth
  APP_NAME: nhlapp

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository 
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # For SonarCloud - fetch full repo

    - name: Tests - setup Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Tests - install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libmariadb3 libmariadb-dev
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
    - name: Tests - run
      run: pytest -vv app

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
# Connect to Azure Container Registry (ACR)
    - uses: azure/docker-login@v1
      with:
        login-server: epamdiplomaacr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    # Container build and push to a Azure Container Registry (ACR)
    - run: |
        docker build . -t epamdiplomaacr.azurecr.io/nhlapp:${{ github.sha }}
        docker push epamdiplomaacr.azurecr.io/nhlapp:${{ github.sha }}
      working-directory: ./app
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        namespacePresent=`kubectl get namespace | grep nhlstat | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace nhlstat`
        fi
    
    # Create image pull secret for ACR
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: epamdiplomaacr.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: nhltauth
        namespace: ${{ env.NAMESPACE }}
        arguments: --force true
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/manifests/deployment.yaml
          ${{ github.workspace }}/manifests/service.yaml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
        imagepullsecrets: |
          nhltauth
        namespace: ${{ env.NAMESPACE }}

